<?php
/**
 *
 * This file is part of the StartPage
 *
 * @copyright (c) Daniël Rokven
 *
 * @license Mit
 *
 * For full copyright and license information, please see
 * the docs/CREDITS.txt file.
 *
 */

namespace App\Controllers;
use SleekDB\Store;
use CodeIgniter\I18n\Time;

class InstallController extends BaseController
{
  public function index()
  {
    if (is_dir(DATABASE_DIR . "/settings"))
    {
      echo 'Startpage is already installed';
      exit;
    }
    $this->admin = model(\App\Models\AdminModel::class);

    $installed_time             = new \DateTime();
    $data["title"]              = 'Install Startpage';
    $data["database_dir_write"] = [];
    helper('date');
    
    if ($this->request->is("post"))
    {
      $base_url       = str_replace('/install', '', 'https://'.$_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
      $adminusername  = !empty($this->request->getPost("administrator_username")) ? str_replace(' ', '', strtolower(esc($this->request->getPost("administrator_username")))) : "StartPage";
      $adminpassword  = !empty($this->request->getPost("password")) ? esc($this->request->getPost("password")) : "StartPage";
      $adminemail     = !empty($this->request->getPost("admin_email")) ? str_replace(' ', '',strtolower(esc($this->request->getPost("admin_email")))) : "startpage@placeholder.dev";

      if (!is_dir(DATABASE_DIR . "/settings"))
      {
        $configuration =
        [
          "auto_cache"          => FALSE,
          "cache_lifetime"      => null,
          "timeout"             => FALSE, // deprecated! Set it to FALSE!
          "primary_key"         => "id",
          "folder_permissions"  => 0777
        ];

        // Begin categories
        $categories_array =
        [
          [//1
            'name'                    =>  'Startpage built with',
            'column'                  =>  '1',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '100',
          ],
          [//2
            'name'                    =>  'Css Frameworks',
            'column'                  =>  '2',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '100',
          ],
          [//3
            'name'                    =>  'Php Frameworks',
            'column'                  =>  '3',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '100',
          ],
          [//4
            'name'                    =>  'Misc',
            'column'                  =>  '4',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '100',
          ],
          [//5
            'name'                    =>  'Forum',
            'column'                  =>  '1',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '99',
          ],
          [//6
            'name'                    =>  'Wiki',
            'column'                  =>  '2',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '99',
          ],
          [//7
            'name'                    =>  'CMS / Portals',
            'column'                  =>  '3',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '99',
          ],
          [//8
            'name'                    =>  'Analytics',
            'column'                  =>  '4',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '99',
          ],
          [//9
            'name'                    =>  'Image Galleries',
            'column'                  =>  '1',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '98',
          ],
          [//10
            'name'                    =>  'eCommerce',
            'column'                  =>  '2',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '98',
          ],
          [//11
            'name'                    =>  'Blog',
            'column'                  =>  '4',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '98',
          ],
          [
            'name'                    =>  'Social Dating',
            'column'                  =>  '2',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '98',
          ],
          [
            'name'                    =>  'LMS / LCMS',
            'column'                  =>  '3',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '98',
          ],
          [
            'name'                    =>  'Lite / Simple',
            'column'                  =>  '4',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '98',
          ],
          [
            'name'                    =>  'Groupware',
            'column'                  =>  '2',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '97',
          ],
          [
            'name'                    =>  'ECM',
            'column'                  =>  '1',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '96',
          ],
          [
            'name'                    =>  'CRM',
            'column'                  =>  '2',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '96',
          ],
          [
            'name'                    =>  'CMF',
            'column'                  =>  '4',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '96',
          ],
          [
            'name'                    =>  'Clan CMS',
            'column'                  =>  '1',
            'numb_links'              =>  '10',
            'icon_left'               =>  '',
            'icon_right'              =>  '',
            'background_color_header' =>  'bg-primary',
            'text_color_header'       =>  'text-light',
            'background_color_footer' =>  'bg-primary',
            'link_color_footer'       =>  'link-light',
            'link_color_list'         =>  'link-dark',
            'visible'                 =>  '1',
            'position'                =>  '95',
          ],
        ];
        // Create Table categories
        $categories = new Store("categories", DATABASE_DIR, $configuration);
        // Insert Array's categories
        $categories->InsertMany($categories_array);
        // End categories

        // Begin links
        $links_array =
        [
          [
            'name'        =>  'Bootstrap',
            'url'         =>  'http://getbootstrap.com',
            'category_id' =>  '1',
            'title'       =>  'Build fast, responsive sites with Bootstrap',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Codeigniter',
            'url'         =>  'http://codeigniter.com',
            'category_id' =>  '1',
            'title'       =>  'The small framework with powerful features',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '&nbsp;<i class="fa-solid fa-t fa-2xs" style="color: #ff0000;"></i><i class="fa-solid fa-i fa-2xs" style="color: #ff0000;"></i><i class="fa-solid fa-p fa-2xs" style="color: #ff0000;"></i>',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'SleekDB',
            'url'         =>  'https://sleekdb.github.io',
            'category_id' =>  '1',
            'title'       =>  'SleekDB - A NoSQL Database made using PHP',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Favicon',
            'url'         =>  'https://favicon.io',
            'category_id' =>  '1',
            'title'       =>  'The only favicon generator you need for your next project. Quickly generate your favicon from text, image, or choose from hundreds of emojis.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Font Awesome',
            'url'         =>  'https://fontawesome.com',
            'category_id' =>  '1',
            'title'       =>  'Take the hassle out of icons in your project.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Bootstrap',
            'url'         =>  'http://getbootstrap.com',
            'category_id' =>  '2',
            'title'       =>  'Build fast, responsive sites with Bootstrap',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Bulma',
            'url'         =>  'https://bulma.io',
            'category_id' =>  '2',
            'title'       =>  'The Modern CSS Framework',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Foundation',
            'url'         =>  'https://get.foundation',
            'category_id' =>  '2',
            'title'       =>  'The most advanced responsive front-end framework in the world.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Materialize',
            'url'         =>  'https://materializecss.github.io/materialize',
            'category_id' =>  '2',
            'title'       =>  'Simple. Built on open source. The responsive front-end library based on Material Design from Google.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Tailwind',
            'url'         =>  'https://tailwindcss.com',
            'category_id' =>  '2',
            'title'       =>  'Rapidly build modern websites without ever leaving your HTML.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Codeigniter',
            'url'         =>  'http://codeigniter.com',
            'category_id' =>  '3',
            'title'       =>  'The small framework with powerful features',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '&nbsp;<i class="fa-solid fa-t fa-2xs" style="color: #ff0000;"></i><i class="fa-solid fa-i fa-2xs" style="color: #ff0000;"></i><i class="fa-solid fa-p fa-2xs" style="color: #ff0000;"></i>',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Laravel',
            'url'         =>  'http://laravel.com',
            'category_id' =>  '3',
            'title'       =>  'The PHP Framework for Web Artisans',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '99',
          ],
          [
            'name'        =>  'Symfony',
            'url'         =>  'https://symfony.com',
            'type'        =>  'list',
            'category_id' =>  '3',
            'title'       =>  'Symfony is a set of reusable PHP components ... and a PHP framework for web projects',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '98',
          ],
          [
            'name'        =>  'Laminas',
            'url'         =>  'https://getlaminas.org',
            'category_id' =>  '3',
            'title'       =>  'Laminas Project, the enterprise-ready PHP Framework and components A community-supported, open source continuation of Zend Framework.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '98',
          ],
          [
            'name'        =>  'Yii',
            'url'         =>  'https://www.yiiframework.com',
            'category_id' =>  '3',
            'title'       =>  'Yii is a fast, secure, and efficient PHP framework. Flexible yet pragmatic. Works right out of the box. Has reasonable defaults.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '97',
          ],
          [
            'name'        =>  'Base64decode',
            'url'         =>  'https://www.base64decode.org',
            'category_id' =>  '4',
            'title'       =>  'Do you have to deal with Base64 format? Then this site is perfect for you! Use our super handy online tool to encode or decode your data.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '97',
          ],
          [
            'name'        =>  'Logo',
            'url'         =>  'https://logo.com',
            'category_id' =>  '4',
            'title'       =>  'Launch your business with a free logo',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '96',
          ],
          [
            'name'        =>  'Tw-elements',
            'url'         =>  'https://tw-elements.com',
            'category_id' =>  '4',
            'title'       =>  'Bootstrap components recreated with Tailwind CSS, but with better design and more functionalities',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '96',
          ],
          [
            'name'        =>  'Validator.w3',
            'url'         =>  'https://validator.w3.org',
            'category_id' =>  '4',
            'title'       =>  'Markup Validation Service Check the markup (HTML, XHTML, …) of Web documents',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '96',
          ],
          [
            'name'        =>  'SMF',
            'url'         =>  'https://www.simplemachines.org',
            'category_id' =>  '5',
            'title'       =>  'Elegant, Effective, Powerful, Free, It\'s that simple',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Bbpress',
            'url'         =>  'https://bbpress.org',
            'category_id' =>  '5',
            'title'       =>  'Forums made simple. Modern, Fast en Free!',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Flarum',
            'url'         =>  'https://flarum.org',
            'category_id' =>  '5',
            'title'       =>  'Discussion forums, for your WordPress.org powered site.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'DokuWiki',
            'url'         =>  'https://www.dokuwiki.org/',
            'category_id' =>  '6',
            'title'       =>  'It\'s better when it\'s simple.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '&nbsp;<i class="fa-solid fa-t fa-2xs" style="color: #ff0000;"></i><i class="fa-solid fa-i fa-2xs" style="color: #ff0000;"></i><i class="fa-solid fa-p fa-2xs" style="color: #ff0000;"></i>',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'MediaWiki',
            'url'         =>  'https://www.mediawiki.org/wiki/MediaWiki',
            'category_id' =>  '6',
            'title'       =>  'MediaWiki is a collaboration and documentation platform brought to you by a vibrant community.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'PmWiki',
            'url'         =>  'https://www.pmwiki.org',
            'category_id' =>  '6',
            'title'       =>  'PmWiki is a wiki-based content-management system (CMS) for collaborative creation and maintenance of websites.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'BoltWire',
            'url'         =>  'https://www.boltwire.com/downloads',
            'category_id' =>  '6',
            'title'       =>  'BoltWire is an easy to use web development system with surprising flexibility and power. Its innovative architecture combined with robust markup, and best-in-class forms processing, make it easy to create engaging and interactive online communes, fast. And best of all, it\'s FREE!',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  '1024 cms',
            'url'         =>  'https://sourceforge.net/projects/cms-cvi',
            'category_id' =>  '7',
            'title'       =>  'Last Update: 2015-03-05',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Joomla',
            'url'         =>  'https://www.joomla.org',
            'category_id' =>  '7',
            'title'       =>  'Joomla! is an award-winning content management system (CMS), which enables you to build web sites and powerful online applications.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Drupal',
            'url'         =>  'https://www.drupal.org',
            'category_id' =>  '7',
            'title'       =>  'Drupal 10.2 is here and improves content modeling, block management, menu and taxonomy organization, permission administration, and more! Still the best digital experience platform(DXP) on the web, proudly open source.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'B2evolution',
            'url'         =>  'https://b2evolution.net',
            'category_id' =>  '7',
            'title'       =>  'b2evolution includes everything you need to build websites for sharing and interacting with your community.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Wordpress',
            'url'         =>  'https://wordpress.org',
            'category_id' =>  '7',
            'title'       =>  'The open source publishing platform of choice for millions of websites worldwide—from creators and small businesses to enterprises.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Typo3',
            'url'         =>  'https://typo3.org',
            'category_id' =>  '7',
            'title'       =>  'TYPO3 CMS is an Open Source Enterprise Content Management System with a large global community, backed by the approximately 900 members of the TYPO3 Association.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Tiki',
            'url'         =>  'https://tiki.org/tiki-index.php',
            'category_id' =>  '7',
            'title'       =>  'The power of Tiki is the smart interaction of its components in an all-in-one-model',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Textpattern',
            'url'         =>  'https://textpattern.com/',
            'category_id' =>  '7',
            'title'       =>  'The small content management system that can handle big ideas',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Serendipity',
            'url'         =>  'https://docs.s9y.org/index.html',
            'category_id' =>  '7',
            'title'       =>  'Serendipity is a PHP-powered weblog engine which gives the user an easy way to maintain a blog. While the default package is designed for the casual blogger, Serendipity offers an expandable framework with the power for professional applications.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Pluxml',
            'url'         =>  'https://pluxml.org',
            'category_id' =>  '7',
            'title'       =>  'Pluxml',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Plume CMS',
            'url'         =>  'https://sourceforge.net/projects/pxsystem/',
            'category_id' =>  '7',
            'title'       =>  'Last Update: 2013-05-21',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Pluck',
            'url'         =>  'https://github.com/pluck-cms/pluck',
            'category_id' =>  '7',
            'title'       =>  'Pluck is a small and simple content management system (CMS), written in PHP. With Pluck, you can easily manage your own website. Pluck focuses on simplicity and ease of use. This makes Pluck an excellent choice for every small website. Licensed under the General Public License (GPL), Pluck is completely open source. This allows you to do with the software whatever you want, as long as the software stays open source.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Pligg',
            'url'         =>  'https://sourceforge.net/projects/pligg/',
            'category_id' =>  '7',
            'title'       =>  'Last Update: 2016-06-13',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Matomo',
            'url'         =>  'https://matomo.org',
            'category_id' =>  '8',
            'title'       =>  'Google Analytics alternative that protects your data and your customer\'s privacy.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Piwigo',
            'url'         =>  'https://piwigo.org',
            'category_id' =>  '9',
            'title'       =>  'Piwigo is open source photo management software. Manage, organize and share your photo easily on the web. Designed for organizations, teams and individuals.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Phpwiki',
            'url'         =>  'https://sourceforge.net/projects/phpwiki/',
            'category_id' =>  '6',
            'title'       =>  'PhpWiki is a WikiWikiWeb clone in PHP. A WikiWikiWeb is a site where anyone can edit the pages through an HTML form. Multiple storage backends, dynamic hyperlinking, themeable, scriptable by plugins, full authentication, ACL\'s.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Canopy',
            'url'         =>  'https://github.com/AppStateESS/canopy',
            'category_id' =>  '7',
            'title'       =>  'Last commits was on Aug 25, 2022',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Phpwcms',
            'url'         =>  'https://www.phpwcms.org',
            'category_id' =>  '7',
            'title'       =>  'Fast, flexible, robust, perfect: phpwcms 1.10.2',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'NucleusCMS',
            'url'         =>  'https://nucleuscms.github.io',
            'category_id' =>  '7',
            'title'       =>  'Sunrise again! NucleusCMS can help you achieve your goals.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Bbclone',
            'url'         =>  'https://www.bbclone.de',
            'category_id' =>  '8',
            'title'       =>  'A PHP based Web Counter on Steroids',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Composer',
            'url'         =>  'https://compo.sr',
            'category_id' =>  '7',
            'title'       =>  'The versatile Content Management System for next generation websites',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Opencart',
            'url'         =>  'https://www.opencart.com',
            'category_id' =>  '10',
            'title'       =>  'The best FREE and open-source eCommerce platform',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Mylittleforum',
            'url'         =>  'https://mylittleforum.net',
            'category_id' =>  '5',
            'title'       =>  'My little forum is a simple PHP and MySQL based internet forum that displays the messages in classical threaded view (tree structure).',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Mybb',
            'url'         =>  'https://mybb.com',
            'category_id' =>  '5',
            'title'       =>  'MyBB is the free and open source forum software powering thousands of engaging, vibrant, and unique communities across the internet.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Minibb',
            'url'         =>  'https://www.minibb.com',
            'category_id' =>  '5',
            'title'       =>  'MiniBB® is a standalone, open source software for building your own Internet forum, it\'s free to download, and highly customizable.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Cakephp',
            'url'         =>  'https://cakephp.org',
            'category_id' =>  '3',
            'title'       =>  'Faster. Simple. Delicious.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Slim',
            'url'         =>  'https://www.slimframework.com',
            'category_id' =>  '3',
            'title'       =>  'Slim is a PHP micro framework that helps you quickly write simple yet powerful web applications and APIs.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Phalcon',
            'url'         =>  'https://phalcon.io',
            'category_id' =>  '3',
            'title'       =>  'A full-stack PHP framework delivered as a C-extension',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Fuelphp',
            'url'         =>  'https://fuelphp.com',
            'category_id' =>  '3',
            'title'       =>  'The Fuel PHP Framework is a fast, simple and flexible PHP 5.4+ framework, born from the best ideas of other frameworks, with a fresh start!',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Lumen',
            'url'         =>  'https://lumen.laravel.com/docs/11.x',
            'category_id' =>  '3',
            'title'       =>  'Lumen is Laravel\'s PHP micro-framework also created by Taylor Otwell and the Laravel community.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Flight',
            'url'         =>  'https://flightphp.com',
            'category_id' =>  '3',
            'title'       =>  'Flight is a fast, simple, extensible framework for PHP. It is quite versatile and can be used for building any kind of web application. It is built with simplicity in mind and is written in a way that is easy to understand and use.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Phpixie',
            'url'         =>  'https://phpixie.com',
            'category_id' =>  '3',
            'title'       =>  'PHPixie is easy to learn and does not rely on automagic. You will always be in charge of what\'s happening.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Normalize',
            'url'         =>  'https://github.com/sindresorhus/modern-normalize',
            'category_id' =>  '2',
            'title'       =>  'Normalize browser\'s default style',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Ress',
            'url'         =>  'https://github.com/filipelinhares/ress',
            'category_id' =>  '2',
            'title'       =>  'Modern CSS reset',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Natural Selection',
            'url'         =>  'https://github.com/frontaid/natural-selection',
            'category_id' =>  '2',
            'title'       =>  'Natural Selection is a CSS framework without any styling at all. It is just a collection of selectors that can be used to define global styles. Natural Selection aims to provide a best-practice CSS boilerplate that can be used to start projects. It tries to encourage semantic HTML and the handling of accessibility concerns.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'MVP',
            'url'         =>  'https://andybrewer.github.io/mvp/',
            'category_id' =>  '2',
            'title'       =>  'No class names, no frameworks, just semantic HTML and you\'re done.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Sakura',
            'url'         =>  'https://oxal.org/projects/sakura/',
            'category_id' =>  '2',
            'title'       =>  'The perfect blossom is a rare thing. You could spend your life looking for one, and it would not be a wasted life',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Simplecss',
            'url'         =>  'https://simplecss.org',
            'category_id' =>  '2',
            'title'       =>  'Simple.css is a CSS framework that makes semantic HTML look good, really quickly.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Tacit',
            'url'         =>  'https://yegor256.github.io/tacit/',
            'category_id' =>  '2',
            'title'       =>  'Tacit is a CSS framework for dummies, who want their web services to look attractive but have almost zero skills in graphic design, just like myself. This is how your website will look if you add just this code to your HTML:',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Purecss',
            'url'         =>  'https://purecss.io',
            'category_id' =>  '2',
            'title'       =>  'A set of small, responsive CSS modules that you can use in every web project.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Uikit',
            'url'         =>  'https://getuikit.com',
            'category_id' =>  '2',
            'title'       =>  'UIkit is a lightweight and modular front-end framework for developing fast and powerful web interfaces.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Primer',
            'url'         =>  'https://primer.style',
            'category_id' =>  '2',
            'title'       =>  'Primer is a set of guidelines, principles, and patterns for designing and building UI at GitHub. It provides a shared language and standardized approach to delivering cohesive experiences.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Picocss',
            'url'         =>  'https://picocss.com',
            'category_id' =>  '2',
            'title'       =>  'Minimal CSS Framework for Semantic HTML',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Picnicss',
            'url'         =>  'https://picnicss.com',
            'category_id' =>  '2',
            'title'       =>  'Picnic CSS Lightweight and beautiful library',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Chota',
            'url'         =>  'https://jenil.github.io/chota/',
            'category_id' =>  '2',
            'title'       =>  'A micro (~3kb) CSS framework.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Carbon',
            'url'         =>  'https://carbondesignsystem.com',
            'category_id' =>  '2',
            'title'       =>  'Carbon is IBM\'s open source design system for products and digital experiences. With the IBM Design Language as its foundation, the system consists of working code, design tools and resources, human interface guidelines, and a vibrant community of contributors.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Fomantic-ui',
            'url'         =>  'https://fomantic-ui.com',
            'category_id' =>  '2',
            'title'       =>  'The official community fork of Semantic-UI',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Blazeui',
            'url'         =>  'https://www.blazeui.com',
            'category_id' =>  '2',
            'title'       =>  'Blaze UI provides great structure for building websites quickly with a scalable and maintainable foundation.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Cirrus CSS',
            'url'         =>  'https://cirrus-ui.netlify.app',
            'category_id' =>  '2',
            'title'       =>  'Create beautiful designs in less time with Cirrus, the SCSS framework designed for rapid prototyping. Use beautiful pre-built components to bootstrap your next project and utility classes to polish your final design.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Vanilla',
            'url'         =>  'https://vanillaframework.io',
            'category_id' =>  '2',
            'title'       =>  'A simple, extensible CSS framework Backed by open-source code and written in Sass by the Canonical Web Team.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Patternfly',
            'url'         =>  'https://www.patternfly.org',
            'category_id' =>  '2',
            'title'       =>  'PatternFly is an open source design system that enables teams to create consistent and scalable enterprise products. PatternFly is sponsored and maintained by Red Hat, but is open to all.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Stacks',
            'url'         =>  'https://stackoverflow.design',
            'category_id' =>  '2',
            'title'       =>  'Stacks provides everything you need to quickly design, build, and ship coherent experiences across all of Stack Overflow—from the brand and product itself, down to how we send emails and write copy.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Hiq',
            'url'         =>  'https://jonathanharrell.github.io/hiq/',
            'category_id' =>  '2',
            'title'       =>  'Jump-start your styling with a lightweight, easily customizable framework that is built with CSS custom properties and modern best practices.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Material Design',
            'url'         =>  'https://m2.material.io/develop/web',
            'category_id' =>  '2',
            'title'       =>  'Build beautiful, usable products using Material Components for the web',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Beer',
            'url'         =>  'https://www.beercss.com',
            'category_id' =>  '2',
            'title'       =>  'Build material design in record time without stress for devs',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Materialize',
            'url'         =>  'https://materializeweb.com',
            'category_id' =>  '2',
            'title'       =>  'Simple. Built on open source. The responsive front-end library based on Material Design from Google.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Open Props',
            'url'         =>  'https://open-props.style',
            'category_id' =>  '2',
            'title'       =>  'Supercharged CSS variables.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Nes.css',
            'url'         =>  'https://nostalgic-css.github.io/NES.css/',
            'category_id' =>  '2',
            'title'       =>  'NES.css is NES-style (8bit-like) CSS Framework.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  '98.css',
            'url'         =>  'https://jdan.github.io/98.css',
            'category_id' =>  '2',
            'title'       =>  'CSS library for building interfaces that look like Windows 98.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Tufte CSS',
            'url'         =>  'https://edwardtufte.github.io/tufte-css',
            'category_id' =>  '2',
            'title'       =>  'Tufte CSS provides tools to style web articles using the ideas demonstrated by Edward Tufte’s books and handouts. Tufte’s style is known for its simplicity, extensive use of sidenotes, tight integration of graphics with text, and carefully chosen typography.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Gutenberg',
            'url'         =>  'https://github.com/BafS/Gutenberg',
            'category_id' =>  '2',
            'title'       =>  'Modern framework to print web pages correctly',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'XP.css',
            'url'         =>  'https://botoxparty.github.io/XP.css/',
            'category_id' =>  '2',
            'title'       =>  'CSS library for building interfaces that look like Windows XP.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'TuiCss',
            'url'         =>  'https://github.com/vinibiavatti1/TuiCss',
            'category_id' =>  '2',
            'title'       =>  'Text-based user interface CSS library',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  '7.css',
            'url'         =>  'https://khang-nd.github.io/7.css',
            'category_id' =>  '2',
            'title'       =>  '7.css is a CSS framework for building interface components that look like Windows 7. It is built on top of the GUI backbone of XP.css, which is an extension of 98.css.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Bojler',
            'url'         =>  'https://bojler.slicejack.com',
            'category_id' =>  '2',
            'title'       =>  'Bojler is an email framework for developing responsive and lightweight email templates that will render correctly across each of the most popular email clients.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Bourbon',
            'url'         =>  'https://www.bourbon.io',
            'category_id' =>  '2',
            'title'       =>  'Bourbon is a lightweight Sass tool set',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'GetSimple CMS',
            'url'         =>  'http://get-simple.info',
            'category_id' =>  '7',
            'title'       =>  'The Simplest Content Management System. Ever.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'glFusion',
            'url'         =>  'https://www.glfusion.org',
            'category_id' =>  '7',
            'title'       =>  'A dynamic system based on flexible and granular permissions, with spam protection, forums, file management, media gallery, calendars, polls, site-wide search, RSS feeds, and more! Frustrated by hunting for compatible 3rd party plugins? glFusion offers it all right out of the box!',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'FUDForum',
            'url'         =>  'https://fudforum.org',
            'category_id' =>  '5',
            'title'       =>  'Fast Uncompromising Discussions. FUDforum will get your users talking.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Flatpress',
            'url'         =>  'https://www.flatpress.org',
            'category_id' =>  '11',
            'title'       =>  'FlatPress is a lightweight, easy-to-set-up blogging engine. Plain and simple, just PHP. No database needed! Being around since 2006, FlatPress is mature and well-tested.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'e107',
            'url'         =>  'https://e107.org',
            'category_id' =>  '7',
            'title'       =>  'e107 is a free website content management system',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Cms made simple',
            'url'         =>  'https://www.cmsmadesimple.org',
            'category_id' =>  '7',
            'title'       =>  'Open Source Content Management System',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Concrete',
            'url'         =>  'https://www.concretecms.com',
            'category_id' =>  '7',
            'title'       =>  'Concrete CMS delivers the power and simplicity your organization needs to create and manage a complex web presence easily and effectively.',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
          [
            'name'        =>  'Websitebaker',
            'url'         =>  'https://websitebaker.org',
            'category_id' =>  '7',
            'title'       =>  'WebsiteBaker helps you to create the website you want: A free, easy and secure, flexible and extensible open source content management system (CMS).',
            'type'        =>  'list',
            'img'         =>  '',
            'html'        =>  '',
            'target'      =>  '1',
            'visible'     =>  '1',
            'icon_left'   =>  '<i class="fa-solid fa-earth-europe"></i>',
            'icon_right'  =>  '',
            'position'    =>  '100',
          ],
        ];
        // Create the Table links
        $categories = new Store("links", DATABASE_DIR, $configuration);
        // Insert the Array's links
        $categories->InsertMany($links_array);
        // End links

        // Begin users
        $users_configuration = [
          "auto_cache"          => FALSE,
          "cache_lifetime"      => null,
          "timeout"             => FALSE, // deprecated! Set it to FALSE!
          "primary_key"         => "user_id",
          "folder_permissions"  => 0777
        ];
        $adminpassword = password_hash($adminpassword,PASSWORD_BCRYPT);
        $users_array =
        [
          "username"        => $adminusername,
          "password"        => $adminpassword,
          "email"           => $adminemail,
          "title"           => "Administrator",
          "time_format"     => "",
          "date_format"     => "",
          "language"        => "eng",
          "style"           => "default",
          "registered"      => time(),
          "registration_ip" => esc($this->request->getIPAddress()),
        ];
        // Create Table users
        $users_table = new Store("users", DATABASE_DIR, $users_configuration);
        // Insert Array's users
        $users_table->Insert($users_array);
        // End users

        // Begin settings
        $settings_array = 
        [
          "title"                         =>  'Startpage',
          "description"                   =>  'The small Startpage with powerful features',
          "html_footer"                   =>  "<footer>Copyright ©</footer>",
          "show_footer"                   =>  '0',
          "version"                       =>  "0.0.1",
          "timestamp_installed"           =>  ''.$installed_time->getTimestamp().'',
          "redirect_time"                 =>  '2',
          "base_url"                      =>  $base_url,
          "email"                         =>  $adminemail,
          "body_background"               =>  "bg-dark-subtle",
          "nav_background"                =>  "bg-primary",
          "nav_link_color"                =>  "link-light",
          "show_login_link"               =>  '1',
          "head"                          =>  '',
          "foot"                          =>  '',
          'default_cat_bg_color_header'   =>  'bg-primary',
          'default_cat_text_color_header' =>  'text-light',
          'default_cat_bg_color_footer'   =>  'bg-primary',
          'default_cat_link_color_footer' =>  'link-light',
          'default_cat_link_color_list'   =>  'link-dark',

        ];
        // Create Table settings
        $settings  = new Store("settings", DATABASE_DIR, $configuration);
        // Insert ARRAY settings
        $settings->Insert($settings_array);
        // End settings

        $settings_table = new Store('settings', DATABASE_DIR);
        $settings_table = $settings_table
          ->CreateQueryBuilder()
          ->disableCache()
          ->getQuery()
          ->fetch();
        $settings_table = array_shift($settings_Table);

        $data['time'] 	          = '2';
        $data['message']          = 'Well Done. Startpage is installed';
        $data['destination_url']  = $settings_table['base_url'];

        return view('Redirect-Template', $data);
      }
      $data['time'] 	          = '2';
      $data['message']          = 'Well Done. Startpage is installed';
      $data['destination_url']  = $settings_table['base_url'];
      return view('Redirect-Template', $data);
    }
    else
    {
      $database_dir_write = is_wriTable(DATABASE_DIR);
      $data["database_dir_write"] = ($database_dir_write) ? 1 : 0;
    }
    return view("Install-Template", $data);
  }
}

/* End of file InstallController.php */
/* Location: ./app/Controllers/InstallController.php */